name: Approval

on:
  workflow_run:
    workflows: ["Build and Deploy"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Determine Stage to Deploy
        id: determine_stage
        run: echo "::set-output name=stage::${{ github.event.workflow_run.conclusion }}"

      - name: Deploy to Dev
        if: steps.determine_stage.outputs.stage == 'success' && github.event.workflow_run.name == 'Build and Deploy - Dev'
        run: |
          # Add your deployment script or commands for the dev environment

      - name: Deploy to Staging
        if: steps.determine_stage.outputs.stage == 'success' && github.event.workflow_run.name == 'Build and Deploy - Staging'
        run: |
          # Add your deployment script or commands for the staging environment

      - name: Deploy to Production
        if: steps.determine_stage.outputs.stage == 'success' && github.event.workflow_run.name == 'Build and Deploy - Production'
        run: |
          # Add your deployment script or commands for the production environment

  manual-approval:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Request Manual Approval
        if: github.event.workflow_run.conclusion == 'success'
        uses: actions/github-script@0.10.0
        with:
          script: |
            const response = await github.graphql(`
              mutation {
                workflowRunApprove(input: {workflowRunId: "${{ github.event.workflow_run.id }}"}) {
                  clientMutationId
                }
              }
            `);
            console.log(response);